version: 2
jobs:
  build-maven:
    docker:
      - image: cimg/openjdk:17.0.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.maven" }}
            - v1-dependencies-
      - run: make build
      - run: mvn clean install jacoco:prepare-agent package jacoco:report

  report-all:
    docker:
      - image: cimg/openjdk:17.0.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: mvn clean install jacoco:prepare-agent package jacoco:report
      - run: mvn omni-coveragereporter:report

workflows:
  version: 2
  build_all:
    jobs:
      - build-maven
      - report-all
