version: 2
jobs:
  build-maven:
    docker:
      - image: cimg/openjdk:17.0.1

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install npm -y
      - run: npm install -g grunt-cli
      - run: make build
      - run: mvn clean install jacoco:prepare-agent package jacoco:report

  report-all:
    docker:
      - image: cimg/openjdk:17.0.1

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install npm -y
      - run: npm install -g grunt-cli
      - run: mvn clean install jacoco:prepare-agent package jacoco:report
      - run: mvn omni-coveragereporter:report

workflows:
  version: 2
  build_all:
    jobs:
      - build-maven
      - report-all
