version: 2
jobs:
  build-maven:
    docker:
      - image: eclipse-temurin:21-alpine

    working_directory: ~/repo

    steps:
      - checkout
      - run: apk update
      - run: apk add maven make build-base autoconf automake
      - run: make build
      - run: mvn clean install jacoco:prepare-agent package jacoco:report

  report-all:
    docker:
      - image: eclipse-temurin:21-alpine

    working_directory: ~/repo

    steps:
      - checkout
      - run: apk update
      - run: apk add maven make build-base autoconf automake
      - run: mvn clean install jacoco:prepare-agent package jacoco:report
      - run: mvn omni-coveragereporter:report

workflows:
  version: 2
  build_all:
    jobs:
      - build-maven
      - report-all
